default_install_hook_types:
- pre-commit
- post-checkout
- pre-push
repos:
- repo: local
  hooks:
  - id: pre-commit-run-cabal-gild
    name: Formats .cabal files with cabal-gild
    always_run: true
    verbose: true
    stages: [commit]
    language: system
    pass_filenames: false
    entry: bash -c "find . -not -path '**/dist-newstyle/**' -and \\( -name '*.cabal' -or -name 'cabal*.project*' \\) -exec cabal-gild --io {} \\;"
